name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./mobile-app
        run: npm install


      - name: Prebuild Android
        working-directory: ./mobile-app
        run: npx expo prebuild --platform android --clean

      - name: Build APK (Gradle)
        working-directory: ./mobile-app/android
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          name: Latest Release
          tag_name: latest
          files: mobile-app/android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
